name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        pip3 install boostedblob
        curl -sSL https://install.python-poetry.org | python3 -
        pip3 install poetry
        poetry install
        poetry shell
    - name: Test with ./test.sh
      run: |
        ./test.sh
